### PR TITLE
All code changes

### PR DESCRIPTION
**Pull request by gem-divyamadan**
Hi @Gem-NeerajSingh,
Kindly review the code for API.

### CODE REVIEW

**Comment by gem-divyamadan** [comment]
@gem-pawandeep pls get it review & merge.
Thanks

**Comment by gem-divyamadan** [comment]
@Gem-NeerajSingh pls get it reviewed & merged in beta branch.

**Review by Gem-NeerajSingh — APPROVED** [review]

**Comment by gem-divyamadan** [comment]
@Gem-NeerajSingh Pls help getting this merge.

**Comment by Gem-NeerajSingh** [comment]
Conflicting files
src/main/java/com/qa/mis/commonutils/Utils.java
src/main/resources/gemjar-config.json

**Review by Gem-NeerajSingh — APPROVED** [review]

**Pull request merged**
